services:
  financial-agent-api:
    container_name: financial-agent-api
    build:
      context: ./codebases/financial-agent-api
      dockerfile: ../../support/financial-agent-api/Dockerfile
    depends_on:
      financial-agent-db:
        condition: service_healthy
    env_file:
      - ./.local-config/llm.env
    environment:
      COMPLAINTS_CSV_PATH: /app/data/complaints/complaints.csv
      DOCS_SOURCE_DIR: /app/data/docs
      DATABASE_URL: postgresql+psycopg://app:app@financial-agent-db:5432/app
    volumes:
      - ./data:/app/data:ro
    networks:
      - financial-agent-network

  financial-agent-db:
    container_name: financial-agent-db
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./.local-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - financial-agent-network

  financial-agent-ui:
    container_name: financial-agent-ui
    build:
      context: ./codebases/financial-agent-ui
      dockerfile: ../../support/financial-agent-ui/Dockerfile
    depends_on:
      financial-agent-api:
        condition: service_started
    volumes:
      - ./codebases/financial-agent-ui/public:/app/public
      - ./codebases/financial-agent-ui/src:/app/src
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000 || exit 1"]
      interval: 5s
      timeout: 60s
      retries: 10
    networks:
      - financial-agent-network

  financial-agent-nginx:
    container_name: financial-agent-nginx
    image: nginx:stable-alpine
    volumes:
      - ./support/financial-agent-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./support/financial-agent-nginx/financial-agent-api.localhost.com.conf:/etc/nginx/conf.d/financial-agent-api.localhost.com.conf:ro
      - ./support/financial-agent-nginx/financial-agent-ui.localhost.com.conf:/etc/nginx/conf.d/financial-agent-ui.localhost.com.conf:ro
    ports:
      - "80:80"
    depends_on:
      financial-agent-api:
        condition: service_started
      financial-agent-ui:
        condition: service_healthy
    networks:
      - financial-agent-network

networks:
  financial-agent-network:
    driver: bridge
